# Generated by Django 6.0.4 on 2026-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantpartner',
            name='partner_code',
            field=models.CharField(blank=True, help_text='XXXX-XXXX-XXXX-XXXX — issued on admin approval', max_length=19, null=True, unique=True),
        ),
    ]
