# Generated by Django 6.0 on 2026-05-29 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuisines/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage off (0–100)', max_digits=5)),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts')], max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g. spicy,bestseller', max_length=255)),
                ('preparation_time_minutes', models.PositiveIntegerField(default=15)),
                ('stock', models.PositiveIntegerField(default=100)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_items/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Addon name, e.g., Extra Cheese', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='restaurant.fooditem')),
            ],
            options={
                'verbose_name': 'Food Addon',
                'verbose_name_plural': 'Food Addons',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variant name, e.g., Small, Medium, Large', max_length=100)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment from base price', max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='restaurant.fooditem')),
            ],
            options={
                'verbose_name': 'Food Variant',
                'verbose_name_plural': 'Food Variants',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cuisine_type', models.CharField(choices=[('nepali', 'Nepali'), ('indian', 'Indian'), ('chinese', 'Chinese'), ('continental', 'Continental'), ('italian', 'Italian'), ('thai', 'Thai'), ('japanese', 'Japanese'), ('fast_food', 'Fast Food'), ('bakery', 'Bakery'), ('cafe', 'Cafe'), ('other', 'Other')], default='other', max_length=50)),
                ('food_category', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('all', 'All Day')], default='all', max_length=20)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_non_veg', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='restaurants/banners/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=5.0, help_text='Delivery radius in kilometres', max_digits=5)),
                ('social_facebook', models.URLField(blank=True)),
                ('social_instagram', models.URLField(blank=True)),
                ('social_website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.restaurant'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.fooditem')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.fooditem')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('restaurant__isnull', False)), fields=('user', 'restaurant'), name='favorite_unique_user_restaurant'), models.UniqueConstraint(condition=models.Q(('food_item__isnull', False)), fields=('user', 'food_item'), name='favorite_unique_user_fooditem')],
            },
        ),
    ]
