# Generated by Django 6.0.4 on 2026-06-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordering_redesign'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='rider_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
