# Generated by Django 6.0.4 on 2026-06-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='citizenship_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='rider_code',
            field=models.CharField(blank=True, help_text='6-character ID issued on admin approval', max_length=6, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='RiderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawable_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='riders.rider')),
            ],
        ),
    ]
